### ISSUE TITLE
femanager 4.0 error opening a folder with BE modul

### ISSUE THREAD

**Issue by Hobokens** [einpraegsam/femanager#45] opened 2017-12-18 20:28 UTC
I'm using TYPO3 8.7.9 with femanager 4.0. I have all users in a folder. When I try to open this folder or any other folder with the femanager BE modul I get the error

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1509296606: Failed to fetch error page `"https://www.mydomain.org/typo3/404.html"`, reason: Client error: `GET https://www.mydomain.org/typo3/404.html resulted in a 404 Not Found response: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"> <html> <head> <meta http-equiv="Content-Type" content="text (truncated...) |` RuntimeException thrown in file /html/typo3/typo3_src-8.7.9/typo3/sysext/frontend/Classes/Controller/TypoScriptFrontendController.php in line 2050. Requested URL: https://www.mydomain.org/typo3/index.php?M=web_FemanagerM1&moduleToken=b4884728928e4ef9f7032e79e8b2bc9897c75800&id=374&`

When I open a page with the Be module activated i can use 'Show all users from all pages (for administrators only)' and see the new list of all users.
I don't have any problems with femanager 3.3.0.

**Comment by einpraegsam** [comment] 2017-12-19 09:50
Please tell me a bit more about the problem. Do you have activated the femanager module or not? And if you click on the module icon and choose any page, the error is shown in backend? Can you provide a screenshot for me?

**Comment by Hobokens** [comment] 2017-12-19 09:56
Yes I have activated the femanager module. 
If I click on the module icon and choose any page there is no error. But if I click on the module icon and choose any folder I get the mentioned error.
I can send you a screenshot later.

**Comment by einpraegsam** [comment] 2017-12-19 10:00
Ok, I can't reproduce this issue as an admin. Opening the backend module and switch between pages and folders without any problems. Did you cleaned all caches after upgrading? Are you logged in as an admin or as an editor?

**Comment by netcoop** [comment] 2017-12-19 10:09
I ran into the same issue: choose module 'Frontend users' and select a sysfolder. If the sysfolder is a subpage of the root page of the site I get 'Page Not Found, The page did not exist or was inaccessible. Reason: ID was not an accessible page'.
If the sysfolder is outside the siteroot I get 'Page Not Found, The page did not exist or was inaccessible. Reason: The requested page does not exist!'.
Only normal pages can be selected.
I tried debugging with xdebug, but the exceptions are thrown before it reaches AbstractController.

**Comment by Hobokens** [comment] 2017-12-19 10:28
Thank you netcoop. You describe the problem much better than I do. 
I'm logged in as admin and cleared all caches in the install tool.

**Comment by netcoop** [comment] 2017-12-19 14:25
The exceptions are thrown in the getPageAndRootline method in TypoScriptFrontendController. That is strange, since we should be in BE-context here. The error occurs when the method gets no page record back from PageRepository->getPage (another frontend class) because of failing FE-access rights..... something is terribly wrong here!

I've tracked it down to this commit:
89655e4... [FEATURE] Add a second backend view to accept/decline users from the module

All this happens because of the presence of BackendUtility->initializeTsFe(), and more specifically the call to $GLOBALS['TSFE']->determineId();

I don't understand why this code gets called here, but removing $GLOBALS['TSFE']->determineId(); and $GLOBALS['TSFE']->getConfigArray(); lines makes the module work. It probably breaks something else (probably SendMailService, as that is what uses the initializeTsFe method). I suppose moving this method to some other class may solve the issue, but as said, I have absolutely no idea why and how this method gets called at this point, setting breakpoints with xdebug suggests it doesn't even get there, but still, the errors are there and commenting out these 2 lines fixes the errors.

**Comment by einpraegsam** [comment] 2017-12-19 15:40
Can you please check what's the first PID of your pagetree in backend. If it's not 1, pls try to change the default value for `pageIdentifier` https://github.com/einpraegsam/femanager/blob/develop/Classes/Utility/BackendUtility.php#L90

**Comment by netcoop** [comment] 2017-12-19 15:45
Hi Alex, that pid is 1, and it's a standard page.

**Comment by netcoop** [comment] 2017-12-19 16:09
removing the line $pageIdentifier = (int)GeneralUtility::_GP('id'); indeed fixes the error. But of course now it always takes the TS from the page with id=1.

**Comment by einpraegsam** [comment] 2017-12-20 10:38
I just pushed a fix to develop branch. Ready for the upcoming release.
Thx for the time that you spent in this issue.

**Closed by einpraegsam** 2017-12-20 10:38 UTC

**Comment by Hobokens** [comment] 2017-12-27 10:34
Thx for solving the problem.
